version: "2"
checks:
  return-statements:
    config:
      threshold: 5
  similar-code:
    enabled: false
  method-complexity:
    config:
      threshold: 6
exclude_patterns:
    - "src/seeders/"
    - "tests/"
