language: node_js

node_js:
  - 14
env:
  global:
    CC_TEST_REPORTER_ID=4dd6c348f4dc3bd263862d89f216ee53711fd433a0cdc74e99d21613c8fc91bc

services:
- postgresql

install:
  - npm install

before_script:
  - psql -c "create database chowfood_test;" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notification:
  - email: false

after_success:
  - npm run coverage
